# Uygulama adı
spring.application.name=yemekhane-backend

# Sunucunun çalışacağı port numarası (Varsayılan 8080)
server.port=8080

# Proje dizinindeki .env dosyasını properties formatında içe aktarır
spring.config.import=file:./.env[.properties]

# MongoDB veritabanı bağlantı adresi (.env dosyasındaki MONGODB_URI değişkenini kullanır)
spring.mongodb.uri=${MONGODB_URI}
